apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pilotdocs
  annotations:
    acme.kubernetes.io/enable: "true"
    acme.kubernetes.io/dns: "dns_gd"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - docs.pilotnexus.io
    secretName: testsecret-tls
  rules:
  - host: docs.pilotnexus.io
    http:
      paths:
      - path: /
        backend:
          serviceName: pilotdocs
          servicePort: 80
